/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package curncy;

/**
 *
 * @author asp
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1_pak_to_usd = new javax.swing.JCheckBox();
        jTextField1_pktous = new javax.swing.JTextField();
        jCheckBox1_usd_to_pak = new javax.swing.JCheckBox();
        jCheckBox2_PKRtoEuros = new javax.swing.JCheckBox();
        jCheckBox4_EurostoPKR = new javax.swing.JCheckBox();
        jCheckBox5_pkr_penn = new javax.swing.JCheckBox();
        jCheckBox6_penntoPkr = new javax.swing.JCheckBox();
        jCheckBox7_pkr_to_denar = new javax.swing.JCheckBox();
        jCheckBox8_denartopkr = new javax.swing.JCheckBox();
        jCheckBox9_pkrtoYen = new javax.swing.JCheckBox();
        jCheckBox10_yentoPKR = new javax.swing.JCheckBox();
        jTextField2_usTOpkr = new javax.swing.JTextField();
        jTextField3_pkrTOeur = new javax.swing.JTextField();
        jTextField4_eurTOpkr = new javax.swing.JTextField();
        jTextField5_pkrTOpen = new javax.swing.JTextField();
        jTextField6_penTOpkr = new javax.swing.JTextField();
        jTextField7_pkrTOdenar = new javax.swing.JTextField();
        jTextField8_denarTOpkr = new javax.swing.JTextField();
        jTextField9_pkrTOyen = new javax.swing.JTextField();
        jTextField10_yenTOpkr = new javax.swing.JTextField();
        jLabel1_pTOus = new javax.swing.JLabel();
        jLabel2_usTOp = new javax.swing.JLabel();
        jLabel3_pTOeu = new javax.swing.JLabel();
        jLabel4_euTOp = new javax.swing.JLabel();
        jLabel5_pTOpen = new javax.swing.JLabel();
        jLabel6_penTOp = new javax.swing.JLabel();
        jLabel7_pTOden = new javax.swing.JLabel();
        jLabel8_denTOp = new javax.swing.JLabel();
        jLabel9_pTOyen = new javax.swing.JLabel();
        jLabel10_yenTOp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox3.setText("jCheckBox3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));

        jCheckBox1_pak_to_usd.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox1_pak_to_usd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1_pak_to_usd.setForeground(new java.awt.Color(51, 255, 51));
        jCheckBox1_pak_to_usd.setText("PKR to US Dollars $");
        jCheckBox1_pak_to_usd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_pak_to_usdActionPerformed(evt);
            }
        });

        jCheckBox1_usd_to_pak.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox1_usd_to_pak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1_usd_to_pak.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox1_usd_to_pak.setText("US Dollars $ to PKR");
        jCheckBox1_usd_to_pak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_usd_to_pakActionPerformed(evt);
            }
        });

        jCheckBox2_PKRtoEuros.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox2_PKRtoEuros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2_PKRtoEuros.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox2_PKRtoEuros.setText("PKR to Euros");
        jCheckBox2_PKRtoEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2_PKRtoEurosActionPerformed(evt);
            }
        });

        jCheckBox4_EurostoPKR.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox4_EurostoPKR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4_EurostoPKR.setForeground(new java.awt.Color(102, 255, 51));
        jCheckBox4_EurostoPKR.setText("Euros to PKR");
        jCheckBox4_EurostoPKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4_EurostoPKRActionPerformed(evt);
            }
        });

        jCheckBox5_pkr_penn.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox5_pkr_penn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5_pkr_penn.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox5_pkr_penn.setText("PKR to Taka");
        jCheckBox5_pkr_penn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5_pkr_pennActionPerformed(evt);
            }
        });

        jCheckBox6_penntoPkr.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox6_penntoPkr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6_penntoPkr.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox6_penntoPkr.setText("Taka to PKR");
        jCheckBox6_penntoPkr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6_penntoPkrActionPerformed(evt);
            }
        });

        jCheckBox7_pkr_to_denar.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox7_pkr_to_denar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7_pkr_to_denar.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox7_pkr_to_denar.setText("PKR TO Deenar");
        jCheckBox7_pkr_to_denar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7_pkr_to_denarActionPerformed(evt);
            }
        });

        jCheckBox8_denartopkr.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox8_denartopkr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8_denartopkr.setForeground(new java.awt.Color(102, 255, 0));
        jCheckBox8_denartopkr.setText("Deenar To PKR");
        jCheckBox8_denartopkr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8_denartopkrActionPerformed(evt);
            }
        });

        jCheckBox9_pkrtoYen.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox9_pkrtoYen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox9_pkrtoYen.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox9_pkrtoYen.setText("PKR To YEN");
        jCheckBox9_pkrtoYen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9_pkrtoYenActionPerformed(evt);
            }
        });

        jCheckBox10_yentoPKR.setBackground(new java.awt.Color(153, 0, 204));
        jCheckBox10_yentoPKR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox10_yentoPKR.setForeground(new java.awt.Color(51, 255, 0));
        jCheckBox10_yentoPKR.setText("YEN to PKR");
        jCheckBox10_yentoPKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10_yentoPKRActionPerformed(evt);
            }
        });

        jLabel1_pTOus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1_pTOus.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1_pTOus.setText("..");

        jLabel2_usTOp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2_usTOp.setForeground(new java.awt.Color(102, 255, 0));
        jLabel2_usTOp.setText("..");

        jLabel3_pTOeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3_pTOeu.setForeground(new java.awt.Color(255, 51, 255));
        jLabel3_pTOeu.setText("..");

        jLabel4_euTOp.setForeground(new java.awt.Color(102, 255, 0));
        jLabel4_euTOp.setText("..");

        jLabel5_pTOpen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5_pTOpen.setForeground(new java.awt.Color(255, 51, 255));
        jLabel5_pTOpen.setText("..");

        jLabel6_penTOp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6_penTOp.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6_penTOp.setText("..");

        jLabel7_pTOden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7_pTOden.setForeground(new java.awt.Color(255, 51, 255));
        jLabel7_pTOden.setText("..");

        jLabel8_denTOp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8_denTOp.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8_denTOp.setText("..");

        jLabel9_pTOyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9_pTOyen.setForeground(new java.awt.Color(255, 51, 255));
        jLabel9_pTOyen.setText("..");

        jLabel10_yenTOp.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10_yenTOp.setText("..");

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setText("CORRUNCY CONVERTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7_pkr_to_denar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox5_pkr_penn)
                                    .addComponent(jCheckBox6_penntoPkr)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2_PKRtoEuros)
                                    .addComponent(jCheckBox9_pkrtoYen)
                                    .addComponent(jCheckBox10_yentoPKR)
                                    .addComponent(jCheckBox8_denartopkr)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox1_usd_to_pak, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox1_pak_to_usd, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox4_EurostoPKR)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4_eurTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3_pkrTOeur, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2_usTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5_pkrTOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6_penTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7_pkrTOdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8_denarTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9_pkrTOyen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10_yenTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1_pktous, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_usTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_pTOus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_pTOeu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_euTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_pTOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_penTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_pTOden, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8_denTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9_pTOyen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10_yenTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1_pak_to_usd)
                            .addComponent(jTextField1_pktous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_pTOus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1_usd_to_pak)
                            .addComponent(jTextField2_usTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_usTOp))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2_PKRtoEuros)
                            .addComponent(jTextField3_pkrTOeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_pTOeu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox4_EurostoPKR)
                            .addComponent(jTextField4_eurTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_euTOp))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5_pkr_penn)
                            .addComponent(jTextField5_pkrTOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_pTOpen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox6_penntoPkr)
                            .addComponent(jTextField6_penTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_penTOp))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox7_pkr_to_denar)
                            .addComponent(jTextField7_pkrTOdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_pTOden))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8_denartopkr))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8_denarTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8_denTOp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox9_pkrtoYen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10_yentoPKR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9_pkrTOyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9_pTOyen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10_yenTOpkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10_yenTOp))))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1_pak_to_usdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_pak_to_usdActionPerformed
        // TODO add your handling code here:
       try{
        if(jCheckBox1_pak_to_usd.isSelected())
        {
            double a1=Double.parseDouble(jTextField1_pktous.getText());
            
            double tot=a1/100;
            
            jLabel1_pTOus.setText(String.valueOf(tot));
        }
       else
       {
            jTextField1_pktous.setText("");
          jLabel1_pTOus.setText("");
       }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox1_pak_to_usdActionPerformed

    private void jCheckBox1_usd_to_pakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_usd_to_pakActionPerformed
        // TODO add your handling code here:
       
        try
        {if(jCheckBox1_usd_to_pak.isSelected())
        {
            double a2=Double.parseDouble(jTextField2_usTOpkr.getText());
            
            double tot=a2*100;
            
            jLabel2_usTOp.setText(String.valueOf(tot));
        }
         else
       {
            jTextField2_usTOpkr.setText("");
          jLabel2_usTOp.setText("");
       }}
        catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox1_usd_to_pakActionPerformed

    private void jCheckBox2_PKRtoEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2_PKRtoEurosActionPerformed
      try{
        if(jCheckBox2_PKRtoEuros.isSelected())
        {
            double a3=Double.parseDouble(jTextField3_pkrTOeur.getText());
            
            double tot=a3/114.97;
            
            jLabel3_pTOeu.setText(String.valueOf(tot));
        }
       else
       {
            jTextField3_pkrTOeur.setText("");
          jLabel3_pTOeu.setText("");
       }}
      catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox2_PKRtoEurosActionPerformed

    private void jCheckBox4_EurostoPKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4_EurostoPKRActionPerformed
        try{
            if(jCheckBox4_EurostoPKR.isSelected())
        {
            double a3=Double.parseDouble(jTextField4_eurTOpkr.getText());
            
            double tot=a3*114.97;
            
            jLabel4_euTOp.setText(String.valueOf(tot));
        }
       else
       {
            jTextField4_eurTOpkr.setText("");
          jLabel4_euTOp.setText("");
       }}
        catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox4_EurostoPKRActionPerformed

    private void jCheckBox5_pkr_pennActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5_pkr_pennActionPerformed
       try
       {if(jCheckBox5_pkr_penn.isSelected())
        {
            double a3=Double.parseDouble(jTextField5_pkrTOpen.getText());
            
            double tot=a3/0.748314;
            
            jLabel5_pTOpen.setText(String.valueOf(tot));
        }
       else
       {
            jTextField5_pkrTOpen.setText("");
          jLabel5_pTOpen.setText("");
       }}
       catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox5_pkr_pennActionPerformed

    private void jCheckBox6_penntoPkrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6_penntoPkrActionPerformed
        try{
        if(jCheckBox6_penntoPkr.isSelected())
        {
            double a3=Double.parseDouble(jTextField6_penTOpkr.getText());
            
            double tot=a3*0.748314;
            
            jLabel6_penTOp.setText(String.valueOf(tot));
        }
       else
       {
            jTextField6_penTOpkr.setText("");
          jLabel6_penTOp.setText("");
       }}
        catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox6_penntoPkrActionPerformed

    private void jCheckBox7_pkr_to_denarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7_pkr_to_denarActionPerformed
     try{
        if(jCheckBox7_pkr_to_denar.isSelected())
        {
            double a3=Double.parseDouble(jTextField7_pkrTOdenar.getText());
            
            double tot=a3/346;
            
            jLabel7_pTOden.setText(String.valueOf(tot));
        }
       else
       {
            jTextField7_pkrTOdenar.setText("");
          jLabel7_pTOden.setText("");
       }
    }
        catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox7_pkr_to_denarActionPerformed

    private void jCheckBox8_denartopkrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8_denartopkrActionPerformed
       try{
        if(jCheckBox8_denartopkr.isSelected())
        {
            double a3=Double.parseDouble(jTextField8_denarTOpkr.getText());
            
            double tot=a3*346;
            
            jLabel8_denTOp.setText(String.valueOf(tot));
        }
       else
       {
            jTextField8_denarTOpkr.setText("");
          jLabel8_denTOp.setText("");
       }}
       catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox8_denartopkrActionPerformed

    private void jCheckBox9_pkrtoYenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9_pkrtoYenActionPerformed
       try{
        if(jCheckBox9_pkrtoYen.isSelected())
        {
            double a3=Double.parseDouble(jTextField9_pkrTOyen.getText());
            
            double tot=a3/1.01256 ;
            
            jLabel9_pTOyen.setText(String.valueOf(tot));
        }
       else
       {
            jTextField9_pkrTOyen.setText("");
          jLabel9_pTOyen.setText("");
       }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox9_pkrtoYenActionPerformed

    private void jCheckBox10_yentoPKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10_yentoPKRActionPerformed
        try{
        if(jCheckBox10_yentoPKR.isSelected())
        {
            double a3=Double.parseDouble(jTextField10_yenTOpkr.getText());
            
            double tot=a3*1.01256 ;
            
            jLabel10_yenTOp.setText(String.valueOf(tot));
        }
       else
       {
            jTextField10_yenTOpkr.setText("");
          jLabel10_yenTOp.setText("");
       }
        }
        catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jCheckBox10_yentoPKRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox10_yentoPKR;
    private javax.swing.JCheckBox jCheckBox1_pak_to_usd;
    private javax.swing.JCheckBox jCheckBox1_usd_to_pak;
    private javax.swing.JCheckBox jCheckBox2_PKRtoEuros;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4_EurostoPKR;
    private javax.swing.JCheckBox jCheckBox5_pkr_penn;
    private javax.swing.JCheckBox jCheckBox6_penntoPkr;
    private javax.swing.JCheckBox jCheckBox7_pkr_to_denar;
    private javax.swing.JCheckBox jCheckBox8_denartopkr;
    private javax.swing.JCheckBox jCheckBox9_pkrtoYen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_yenTOp;
    private javax.swing.JLabel jLabel1_pTOus;
    private javax.swing.JLabel jLabel2_usTOp;
    private javax.swing.JLabel jLabel3_pTOeu;
    private javax.swing.JLabel jLabel4_euTOp;
    private javax.swing.JLabel jLabel5_pTOpen;
    private javax.swing.JLabel jLabel6_penTOp;
    private javax.swing.JLabel jLabel7_pTOden;
    private javax.swing.JLabel jLabel8_denTOp;
    private javax.swing.JLabel jLabel9_pTOyen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10_yenTOpkr;
    private javax.swing.JTextField jTextField1_pktous;
    private javax.swing.JTextField jTextField2_usTOpkr;
    private javax.swing.JTextField jTextField3_pkrTOeur;
    private javax.swing.JTextField jTextField4_eurTOpkr;
    private javax.swing.JTextField jTextField5_pkrTOpen;
    private javax.swing.JTextField jTextField6_penTOpkr;
    private javax.swing.JTextField jTextField7_pkrTOdenar;
    private javax.swing.JTextField jTextField8_denarTOpkr;
    private javax.swing.JTextField jTextField9_pkrTOyen;
    // End of variables declaration//GEN-END:variables
}
