
import javax.swing.ButtonGroup;
import javax.swing.JTextField;

class InvalidException extends Exception
{
    String msg;
    InvalidException(String s)
    {
        msg=s;
    }
    String printError()
    {
        return "Radius is invalid "+msg;
    }
}
public class lab6 extends javax.swing.JFrame {
    ButtonGroup b=new ButtonGroup();
    
    /**
     * Creates new form lab6
     */
    public lab6() {
       
        initComponents();
         jTextField_num.setEnabled(false);
        jTextField_den.setEnabled(false);
        jTextField_rad.setEnabled(false);
        jTextField_x.setEnabled(false);
        jTextField_y.setEnabled(false);
        b.add(jRadioButton_dividedby);
        b.add(jRadioButton_numberformat);
        b.add(jRadioButton_invalid);
        b.add(jRadioButton_square);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton_dividedby = new javax.swing.JRadioButton();
        jRadioButton_square = new javax.swing.JRadioButton();
        jRadioButton_numberformat = new javax.swing.JRadioButton();
        jRadioButton_invalid = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_num = new javax.swing.JTextField();
        jTextField_den = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_x = new javax.swing.JTextField();
        jTextField_y = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_rad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_show = new javax.swing.JTextArea();
        jButton_res = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton_dividedby.setText("Divided By zero");
        jRadioButton_dividedby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_dividedbyActionPerformed(evt);
            }
        });

        jRadioButton_square.setText("Square root");
        jRadioButton_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_squareActionPerformed(evt);
            }
        });

        jRadioButton_numberformat.setText("Number Format Exception");
        jRadioButton_numberformat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_numberformatActionPerformed(evt);
            }
        });

        jRadioButton_invalid.setText("Invalid Radius");
        jRadioButton_invalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_invalidActionPerformed(evt);
            }
        });

        jLabel1.setText("Numerator");

        jLabel2.setText("Denominator");

        jTextField_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numActionPerformed(evt);
            }
        });

        jTextField_den.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_denActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Result");

        jLabel4.setText("X");

        jLabel5.setText("Y");

        jTextField_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_xActionPerformed(evt);
            }
        });

        jTextField_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_yActionPerformed(evt);
            }
        });

        jLabel6.setText("Radius");

        jTextArea_show.setColumns(20);
        jTextArea_show.setRows(5);
        jScrollPane1.setViewportView(jTextArea_show);

        jButton_res.setText("Show Result");
        jButton_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Exception Handling");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_square)
                                    .addComponent(jRadioButton_dividedby)
                                    .addComponent(jRadioButton_invalid)
                                    .addComponent(jRadioButton_numberformat))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_num, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_den, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_x, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_y, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_rad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_res)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel7)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jRadioButton_dividedby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_square)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_invalid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_numberformat)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_den, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_rad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_res)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resActionPerformed
        if(jRadioButton_dividedby.isSelected())
        {
            String s1=jTextField_num.getText();
            String s2=jTextField_den.getText();
            int n=Integer.parseInt(s1);
            int d=Integer.parseInt(s2);
            try{
                float divide=n/d;
                jTextArea_show.setText("Division Result = "+divide);
            }
            catch(Exception e)
            {
                jTextArea_show.setText("Error Occured "+e);
            }
        }
        if(jRadioButton_square.isSelected())
        {
            String s3=jTextField_x.getText();
            double sqroot=Double.parseDouble(s3);
            try{
                jTextArea_show.setText("Square Root = "+Math.sqrt(sqroot));
            }
            catch(Exception e)
            {
                jTextArea_show.setText("Error Occured "+e);
            }
        }
        if(jRadioButton_invalid.isSelected())
        {
            String s4=jTextField_y.getText();
            try{
                int i=Integer.parseInt(s4);
                jTextArea_show.setText("Number after parsing "+i);
            }
            catch(Exception e)
            {
                jTextArea_show.setText("Error Occured : \n"+e);
            }
        }
        if(jRadioButton_numberformat.isSelected())
        {
            String s5=jTextField_rad.getText();
            Double r=Double.parseDouble(s5);
            if(r>0)
            {
                jTextArea_show.setText("Valid Radius Circle is created : "+r);
            }
            else
            {
                try{
                    throw new InvalidException("Error");
                }
                catch(Exception e)
                {
                    jTextArea_show.setText("Error Occured : \n"+e);
                }
            }
        }
    }//GEN-LAST:event_jButton_resActionPerformed

    private void jTextField_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_yActionPerformed

    private void jTextField_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_xActionPerformed

    private void jTextField_denActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_denActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_denActionPerformed

    private void jTextField_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numActionPerformed

    private void jRadioButton_invalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_invalidActionPerformed
        jTextField_y.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_invalidActionPerformed

    private void jRadioButton_numberformatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_numberformatActionPerformed
        jTextField_rad.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_numberformatActionPerformed

    private void jRadioButton_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_squareActionPerformed
        jTextField_x.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_squareActionPerformed

    private void jRadioButton_dividedbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_dividedbyActionPerformed
        jTextField_num.setEnabled(true);
        jTextField_den.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_dividedbyActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_res;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_dividedby;
    private javax.swing.JRadioButton jRadioButton_invalid;
    private javax.swing.JRadioButton jRadioButton_numberformat;
    private javax.swing.JRadioButton jRadioButton_square;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_show;
    private javax.swing.JTextField jTextField_den;
    private javax.swing.JTextField jTextField_num;
    private javax.swing.JTextField jTextField_rad;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_y;
    // End of variables declaration//GEN-END:variables
}
